# Generated by Django 3.1.1 on 2020-10-02 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base_Picture_Heading_1', models.CharField(max_length=100)),
                ('Base_Picture_Heading_2', models.CharField(max_length=100)),
                ('Heading_1', models.CharField(max_length=100)),
                ('Description_1', models.CharField(max_length=1000)),
                ('Heading_2', models.CharField(max_length=100)),
                ('Description_2', models.CharField(max_length=1000)),
                ('Heading_3', models.CharField(max_length=100)),
                ('Description_3', models.CharField(max_length=1000)),
                ('Heading_4', models.CharField(max_length=100)),
                ('Description_4', models.CharField(max_length=1000)),
                ('Heading_5', models.CharField(max_length=100)),
                ('Description_5', models.CharField(max_length=1000)),
                ('Heading_6', models.CharField(max_length=100)),
                ('Description_6', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Slide_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture_1', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_2', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_3', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_4', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_5', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_6', models.ImageField(default='default.jpg', upload_to='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base_Picture', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_2', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_3', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_4', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_5', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_6', models.ImageField(default='default.jpg', upload_to='Picture')),
                ('Picture_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venue.slide_picture')),
            ],
        ),
    ]
